#!/usr/bin/env node

/**
 * AgentOS Build Script
 *
 * Builds the TypeScript source and generates a combined bundle
 * for DevTools injection.
 */

import * as esbuild from 'esbuild';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');

/** Build configuration */
const config = {
  entryPoint: path.join(ROOT, 'src/index.ts'),
  outDir: path.join(ROOT, 'dist'),
  bundleName: 'agentOS-combined.js',
  minBundleName: 'agentOS.min.js'
};

/**
 * Clean output directory
 */
function clean() {
  if (fs.existsSync(config.outDir)) {
    fs.rmSync(config.outDir, { recursive: true });
  }
  fs.mkdirSync(config.outDir, { recursive: true });
  console.log('[Build] Cleaned output directory');
}

/**
 * Build TypeScript source
 */
async function buildTypeScript() {
  console.log('[Build] Compiling TypeScript...');

  try {
    // Development build
    await esbuild.build({
      entryPoints: [config.entryPoint],
      bundle: true,
      outfile: path.join(config.outDir, config.bundleName),
      format: 'iife',
      globalName: 'AgentOSModule',
      target: ['es2020'],
      platform: 'browser',
      sourcemap: true,
      define: {
        'process.env.NODE_ENV': '"development"'
      },
      banner: {
        js: `/**
 * AgentOS - Multi-Agent Orchestration System
 * Version: 1.0.0
 * Built: ${new Date().toISOString()}
 *
 * Paste this script into DevTools console to initialize AgentOS.
 */
`
      },
      footer: {
        js: `
// Auto-initialize and expose globals
(function() {
  'use strict';
  if (typeof window !== 'undefined') {
    // Expose main exports
    window.AgentOS = AgentOSModule;
    window.EventBus = AgentOSModule.EventBus;
    window.StateManager = AgentOSModule.StateManager;
    window.SignalParser = AgentOSModule.SignalParser;
    window.IntegrationRegistry = AgentOSModule.IntegrationRegistry;
    window.SsoDetector = AgentOSModule.SsoDetector;
    window.SsoHandler = AgentOSModule.SsoHandler;
    window.BrowserAutomation = AgentOSModule.BrowserAutomation;
    window.PageScraper = AgentOSModule.PageScraper;
    window.WorkflowTracker = AgentOSModule.WorkflowTracker;
    window.WorkflowAnalyzer = AgentOSModule.WorkflowAnalyzer;
    window.SkillLoader = AgentOSModule.SkillLoader;
    window.SkillExecutor = AgentOSModule.SkillExecutor;
    window.PollManager = AgentOSModule.PollManager;

    // Initialize
    AgentOSModule.init().then(function() {
      console.log('%c[AgentOS] Ready!', 'color: #4fc3f7; font-weight: bold');
      console.log('Available globals: AgentOS, EventBus, StateManager, IntegrationRegistry, SsoDetector, ...');
    });
  }
})();
`
      }
    });

    console.log('[Build] Development build complete');

    // Production build (minified)
    await esbuild.build({
      entryPoints: [config.entryPoint],
      bundle: true,
      outfile: path.join(config.outDir, config.minBundleName),
      format: 'iife',
      globalName: 'AgentOSModule',
      target: ['es2020'],
      platform: 'browser',
      minify: true,
      define: {
        'process.env.NODE_ENV': '"production"'
      },
      banner: {
        js: `/* AgentOS v1.0.0 | ${new Date().toISOString()} */`
      },
      footer: {
        js: `(function(){if(typeof window!=='undefined'){window.AgentOS=AgentOSModule;AgentOSModule.init()}})();`
      }
    });

    console.log('[Build] Production build complete');

  } catch (error) {
    console.error('[Build] Error:', error);
    process.exit(1);
  }
}

/**
 * Generate type declarations
 */
function generateTypes() {
  console.log('[Build] Type declarations will be generated by tsc');
}

/**
 * Copy static assets
 */
function copyAssets() {
  // Copy skill schemas
  const skillsDir = path.join(ROOT, 'skills');
  const distSkillsDir = path.join(config.outDir, 'skills');

  if (fs.existsSync(skillsDir)) {
    fs.cpSync(skillsDir, distSkillsDir, { recursive: true });
    console.log('[Build] Copied skills directory');
  }

  // Copy agent configs
  const agentsDir = path.join(ROOT, 'agents');
  const distAgentsDir = path.join(config.outDir, 'agents');

  if (fs.existsSync(agentsDir)) {
    fs.cpSync(agentsDir, distAgentsDir, { recursive: true });
    console.log('[Build] Copied agents directory');
  }
}

/**
 * Print build summary
 */
function printSummary() {
  const bundlePath = path.join(config.outDir, config.bundleName);
  const minBundlePath = path.join(config.outDir, config.minBundleName);

  const bundleSize = fs.existsSync(bundlePath)
    ? (fs.statSync(bundlePath).size / 1024).toFixed(2)
    : '?';

  const minBundleSize = fs.existsSync(minBundlePath)
    ? (fs.statSync(minBundlePath).size / 1024).toFixed(2)
    : '?';

  console.log('\n[Build] Summary:');
  console.log(`  Development: ${config.bundleName} (${bundleSize} KB)`);
  console.log(`  Production:  ${config.minBundleName} (${minBundleSize} KB)`);
  console.log(`  Output:      ${config.outDir}`);
  console.log('\n[Build] To use, paste the bundle contents into DevTools console.');
}

/**
 * Main build process
 */
async function main() {
  console.log('[Build] Starting AgentOS build...\n');

  clean();
  await buildTypeScript();
  generateTypes();
  copyAssets();
  printSummary();

  console.log('\n[Build] Done!');
}

main().catch(console.error);
